version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/var/www/html/index.php   
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    build: .
    image: php:7.4-fpm
    volumes:
      - ./index.php:/var/www/html/index.php
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha1234
      MYSQL_DATABASE: mydatabase 
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local 